/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SubscriptionManagerFLOW {
  export type SubscriptionStruct = {
    id: BigNumberish;
    subscriber: AddressLike;
    recipient: AddressLike;
    amountPerCycle: BigNumberish;
    frequency: BigNumberish;
    nextDueAt: BigNumberish;
    active: boolean;
    createdAt: BigNumberish;
  };

  export type SubscriptionStructOutput = [
    id: bigint,
    subscriber: string,
    recipient: string,
    amountPerCycle: bigint,
    frequency: bigint,
    nextDueAt: bigint,
    active: boolean,
    createdAt: bigint
  ] & {
    id: bigint;
    subscriber: string;
    recipient: string;
    amountPerCycle: bigint;
    frequency: bigint;
    nextDueAt: bigint;
    active: boolean;
    createdAt: bigint;
  };
}

export interface SubscriptionManagerFLOWInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancel"
      | "getSubscription"
      | "getSubscriptionsBySubscriber"
      | "isPaymentDue"
      | "nextSubscriptionId"
      | "pay"
      | "subscribe"
      | "subscriptions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PaymentMade"
      | "SubscriptionCancelled"
      | "SubscriptionCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscriptionsBySubscriber",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPaymentDue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextSubscriptionId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pay", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscriptionsBySubscriber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPaymentDue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextSubscriptionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
}

export namespace PaymentMadeEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    subscriber: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    nextDueAt: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    subscriber: string,
    recipient: string,
    amount: bigint,
    nextDueAt: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    subscriber: string;
    recipient: string;
    amount: bigint;
    nextDueAt: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCancelledEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    subscriber: AddressLike,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    subscriber: string,
    recipient: string
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    subscriber: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCreatedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    subscriber: AddressLike,
    recipient: AddressLike,
    amountPerCycle: BigNumberish,
    frequency: BigNumberish,
    nextDueAt: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    subscriber: string,
    recipient: string,
    amountPerCycle: bigint,
    frequency: bigint,
    nextDueAt: bigint
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    subscriber: string;
    recipient: string;
    amountPerCycle: bigint;
    frequency: bigint;
    nextDueAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SubscriptionManagerFLOW extends BaseContract {
  connect(runner?: ContractRunner | null): SubscriptionManagerFLOW;
  waitForDeployment(): Promise<this>;

  interface: SubscriptionManagerFLOWInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancel: TypedContractMethod<
    [subscriptionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getSubscription: TypedContractMethod<
    [subscriptionId: BigNumberish],
    [SubscriptionManagerFLOW.SubscriptionStructOutput],
    "view"
  >;

  getSubscriptionsBySubscriber: TypedContractMethod<
    [subscriber: AddressLike],
    [bigint[]],
    "view"
  >;

  isPaymentDue: TypedContractMethod<
    [subscriptionId: BigNumberish],
    [boolean],
    "view"
  >;

  nextSubscriptionId: TypedContractMethod<[], [bigint], "view">;

  pay: TypedContractMethod<[subscriptionId: BigNumberish], [void], "payable">;

  subscribe: TypedContractMethod<
    [
      recipient: AddressLike,
      amountPerCycle: BigNumberish,
      frequency: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  subscriptions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, boolean, bigint] & {
        id: bigint;
        subscriber: string;
        recipient: string;
        amountPerCycle: bigint;
        frequency: bigint;
        nextDueAt: bigint;
        active: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[subscriptionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getSubscription"
  ): TypedContractMethod<
    [subscriptionId: BigNumberish],
    [SubscriptionManagerFLOW.SubscriptionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubscriptionsBySubscriber"
  ): TypedContractMethod<[subscriber: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isPaymentDue"
  ): TypedContractMethod<[subscriptionId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextSubscriptionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pay"
  ): TypedContractMethod<[subscriptionId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      amountPerCycle: BigNumberish,
      frequency: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subscriptions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, boolean, bigint] & {
        id: bigint;
        subscriber: string;
        recipient: string;
        amountPerCycle: bigint;
        frequency: bigint;
        nextDueAt: bigint;
        active: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "PaymentMade"
  ): TypedContractEvent<
    PaymentMadeEvent.InputTuple,
    PaymentMadeEvent.OutputTuple,
    PaymentMadeEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCancelled"
  ): TypedContractEvent<
    SubscriptionCancelledEvent.InputTuple,
    SubscriptionCancelledEvent.OutputTuple,
    SubscriptionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCreated"
  ): TypedContractEvent<
    SubscriptionCreatedEvent.InputTuple,
    SubscriptionCreatedEvent.OutputTuple,
    SubscriptionCreatedEvent.OutputObject
  >;

  filters: {
    "PaymentMade(uint256,address,address,uint256,uint256,uint256)": TypedContractEvent<
      PaymentMadeEvent.InputTuple,
      PaymentMadeEvent.OutputTuple,
      PaymentMadeEvent.OutputObject
    >;
    PaymentMade: TypedContractEvent<
      PaymentMadeEvent.InputTuple,
      PaymentMadeEvent.OutputTuple,
      PaymentMadeEvent.OutputObject
    >;

    "SubscriptionCancelled(uint256,address,address)": TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;
    SubscriptionCancelled: TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;

    "SubscriptionCreated(uint256,address,address,uint256,uint8,uint256)": TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;
    SubscriptionCreated: TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;
  };
}
